# Create: kubectl apply -f service-a-service.yaml
# Delete: kubectl delete service service-a-service
# List:   kubectl get svc
#         kubectl get services

apiVersion: v1
kind: Service
metadata:
  name: service-a-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: service_a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
